"""First migration

Revision ID: 17fd26dd9f77
Revises: 
Create Date: 2022-07-10 18:51:20.002375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17fd26dd9f77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('сustomer_name', sa.String(), nullable=True),
    sa.Column('customer_address', sa.String(), nullable=True),
    sa.Column('addr_cords', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('created', 'pending', 'awaiting', 'processing', 'submitted', name='orderstatus'), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Order')
    # ### end Alembic commands ###
